import localFont from "next/font/local"

import { cn } from "@/lib/utils"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

const IranSans = localFont({
  src: [
    {
      path: "/../public/fonts/IRANSansX-Regular.ttf",
      style: "normal",
      weight: "normal",
    },
  ],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(IranSans.className)}>{children}</body>
    </html>
  )
}
